### ISSUE TITLE
Refactor: Signup Form

### ISSUE THREAD

**Issue by sonylomo** [Soft-Craft-Tech/pamba-web-client#78]
## Description

- The current sign-up form limits users to selecting from pre-existing business categories. We want to give users the option to add a new category.
- The signup form currently does not validate the phone number.
- The city input accepts any value.
- The MapURL doesn't validate google urls

## Task

- [x] Allow the user to add a custom category when no existing options are available.
- [x] Implement phone number validation using Phonelib and Zod.
- [x] Convert the city input to a select input with a list of cities.
- [x] Use regex to validate mapURL

**Comment by Soft-Craft-Tech** [comment]
I hope this is fixed.
